### ISSUE TITLE
Add icons to external links

### ISSUE THREAD

**Issue by mgwalker** [18F/product-guide#176]
**Background**

External links need some kind of identification to help users know where they're going. With the UX guide and Methods sites, we added some client-side code to handle that. The product guide should be able to incorporate the same code.

@kmori If this is something you want, I'll volunteer to implement it! I'll be opening two more issues about copying stuff from the UX guide and Methods sites and if you want them, I can roll them all into one PR.

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] Links to external sites are identified
- [ ] External link identification is accessible to all users

**Tasks**
- [ ] PO review
- [ ] Accessibility review [if needed]

**Comment by kmori** [comment]
@mgwalker - yes please! would love to make it consistent with UX guide and methods sites!
