### ISSUE TITLE
Add automated tests for links

### ISSUE THREAD

**Issue by mgwalker** [18F/product-guide#178]
**Background**

There are some pre-built testing packages we can use to test that:
- all links are HTTPS
- links to other pages/parts of pages are valid (they point to actual pages)
- links to other pages are formatted correctly (they are not "root-relative" but start with `{{ site.baseurl }}`) so they work in preview

For the UX guide and Methods repos, adding these tests immediately identified a bunch of broken/invalid links. I'd recommend making a separate issue for fixing any problems that the tests find rather than trying to fix them at the same time as adding the tests.

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] tests run on pull requests
- [ ] tests identify invalid links

**Tasks**
- [ ] PO review [if task involves content changes]
